spring.application.name=PasteleriaVelazquezSpring

# ============
# MySQL (AJUSTA usuario/clave)
# ============
spring.datasource.url=jdbc:mysql://localhost:3306/pasteleriaVelazquez?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=

# ============
# JPA / Hibernate
# ============
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
server.port=8081